blueprint:
  name: "Philips Hue Dimmer: Scene Control"
  description: "Scene cycling and dimming control with automatic state-based reset."
  domain: automation
  input:
    remote_device:
      name: Hue Dimmer Remote
      selector:
        device:
          filter:
            - integration: zha
            - manufacturer: Philips
    target_entity:
      name: Target Entity
      description: The light group or fan to control.
      selector:
        target: {}
    scene_helper:
      name: Scene Tracker Helper
      description: The Dropdown (input_select) for this room's scenes.
      selector:
        entity:
          domain: input_select
    area_prefix:
      name: Area Prefix
      description: "The prefix for your scene IDs (e.g., 'living_room')."
      default: ""
    reset_timeout:
      name: Reset Timeout
      description: "Seconds of inactivity before the next press starts at the first scene."
      default: 300
      selector:
        number:
          min: 1
          max: 3600
          unit_of_measurement: seconds

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote_device

action:
  - variables:
      helper: !input scene_helper
      prefix: !input area_prefix
      target: !input target_entity
      timeout_seconds: !input reset_timeout

  - choose:
      # ON BUTTON: PRESS
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'on_press' }}"
        sequence:
          - choose:
            - conditions:
                - condition: template
                  value_template: >
                    {% set ent_id = target.entity_id if target.entity_id is string else target.entity_id[0] %}
                    {% set last_triggered = state_attr(this.entity_id, 'last_triggered') %}
                    {% set inactive = (now() - last_triggered).total_seconds() > timeout_seconds if last_triggered else true %}
                    {{ is_state(ent_id, 'off') or inactive }}
              sequence:
                - service: input_select.select_first
                  target:
                    entity_id: !input scene_helper
            default:
              - service: input_select.select_next
                target:
                  entity_id: !input scene_helper

          - service: scene.turn_on
            target:
              entity_id: "scene.{{ prefix }}_{{ states(helper) | lower | replace(' ', '_') }}"

          # Anti-bounce to prevent double-skipping
          - delay:
              milliseconds: 400

      # UP BUTTON: HOLD
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'up_hold' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ repeat.index < 20 }}"
              sequence:
                - service: light.turn_on
                  target: !input target_entity
                  data:
                    brightness_step_pct: 10
                - wait_for_trigger:
                    - platform: event
                      event_type: zha_event
                      event_data:
                        device_id: !input remote_device
                        command: up_release
                  timeout:
                    seconds: 1
                - condition: template
                  value_template: "{{ wait.trigger == none }}"

      # OFF BUTTON: PRESS
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'off_press' }}"
        sequence:
          # PREVENT LOOP: Only fire off command if target is not already off
          - condition: template
            value_template: >
              {% set ent_id = target.entity_id if target.entity_id is string else target.entity_id[0] %}
              {{ not is_state(ent_id, 'off') }}
          - service: light.turn_off
            target: !input target_entity

      # DOWN BUTTON: HOLD
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'down_hold' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ repeat.index < 20 }}"
              sequence:
                - service: light.turn_on
                  target: !input target_entity
                  data:
                    brightness_step_pct: -10
                - wait_for_trigger:
                    - platform: event
                      event_type: zha_event
                      event_data:
                        device_id: !input remote_device
                        command: down_release
                  timeout:
                    seconds: 1
                - condition: template
                  value_template: "{{ wait.trigger == none }}"
mode: single
