blueprint:
  name: "Logic: Disco Mode"
  description: "Rapidly cycles every light in selected areas to a unique, saturated random color."
  domain: script
  input:
    target_areas:
      name: Areas or Groups
      selector:
        target:
          entity:
            domain: light
    brightness_level:
      name: Brightness
      default: 100
      selector:
        number: { min: 1, max: 100, unit_of_measurement: "%" }
    transition_time:
      name: Transition Speed
      default: 0.3
      selector:
        number: { min: 0.1, max: 2, step: 0.1, unit_of_measurement: "s" }
    delay_time:
      name: Refresh Rate
      default: 0.8
      selector:
        number: { min: 0.1, max: 5, step: 0.1, unit_of_measurement: "s" }

sequence:
  - variables:
      brightness: !input brightness_level
      delay_secs: !input delay_time
      targets: !input target_areas
      transition_secs: !input transition_time
      all_entities: >
        {% set entities = area_entities(targets.area_id) if targets.area_id is string else [] %}
        {% if targets.area_id is list %}
          {% for area in targets.area_id %}
            {% set entities = entities + area_entities(area) %}
          {% endfor %}
        {% endif %}
        {% if targets.entity_id is string %}
          {% set entities = entities + [targets.entity_id] %}
        {% elif targets.entity_id is list %}
          {% set entities = entities + targets.entity_id %}
        {% endif %}
        {{ entities | select('match', 'light.') | unique | list }}
      color_lights: >
        {% set filtered = namespace(entities=[]) %}
        {% for entity in all_entities %}
          {% set modes = state_attr(entity, 'supported_color_modes') or [] %}
          {% if 'hs' in modes or 'rgb' in modes or 'xy' in modes or 'color_temp' in modes %}
            {% set filtered.entities = filtered.entities + [entity] %}
          {% endif %}
        {% endfor %}
        {{ filtered.entities }}
      strobe_lights: >
        {{ all_entities | reject('in', color_lights) | list }}

  - repeat:
      while:
        - condition: template
          value_template: "{{ true }}"
      sequence:
        # Color Service: Sends HS commands which HA translates to XY for your BR30s
        - if:
            - condition: template
              value_template: "{{ color_lights | count > 0 }}"
          then:
            - service: light.turn_on
              target:
                entity_id: "{{ color_lights }}"
              data:
                brightness_pct: "{{ brightness }}"
                hs_color:
                  - "{{ range(0, 360) | random }}"
                  - 100
                transition: "{{ transition_secs }}"
        
        # Strobe Service: Handles Tetris lamps and non-color entities
        - if:
            - condition: template
              value_template: "{{ strobe_lights | count > 0 }}"
          then:
            - service: light.turn_on
              target:
                entity_id: "{{ strobe_lights }}"
              data:
                brightness_pct: "{{ [0, brightness | int] | random }}"
                transition: 0.1
        
        - delay:
            seconds: "{{ delay_secs }}"
mode: restart
