blueprint:
  name: "Logic: Random Color Bop"
  description: "Rapidly cycle random colors by updating a subset of lights per iteration. Creates organic multi-color party lighting effects."
  domain: script
  input:
    target_areas:
      name: Areas or Groups
      selector:
        target:
          entity:
            domain: light
    brightness_level:
      name: Brightness
      default: 100
      selector:
        number: { min: 1, max: 100, unit_of_measurement: "%" }
    transition_time:
      name: Transition Speed
      default: 0.3
      selector:
        number: { min: 0.1, max: 2, step: 0.1, unit_of_measurement: "s" }
    delay_time:
      name: Refresh Rate
      default: 0.8
      selector:
        number: { min: 0.1, max: 5, step: 0.1, unit_of_measurement: "s" }
    bop_count:
      name: Bop Count
      description: Number of lights to change per cycle.
      default: 3
      selector:
        number: { min: 1, max: 20 }

sequence:
  - variables:
      bop_num: !input bop_count
      brightness: !input brightness_level
      delay_secs: !input delay_time
      targets: !input target_areas
      transition_secs: !input transition_time

      # Expand handles infinite nesting and areas automatically
      all_entities: >
        {% set ns = namespace(raw=[]) %}
        {# Collect IDs from selected areas #}
        {% set areas = targets.area_id if targets.area_id is list else ([targets.area_id] if targets.area_id is string else []) %}
        {% for a in areas %}
          {% set ns.raw = ns.raw + area_entities(a) %}
        {% endfor %}
        {# Collect IDs from selected entities #}
        {% set entities = targets.entity_id if targets.entity_id is list else ([targets.entity_id] if targets.entity_id is string else []) %}
        {% set ns.raw = ns.raw + entities %}
        {# The 'expand' filter flattens all nested groups into individual entities #}
        {{ expand(ns.raw) | map(attribute='entity_id') | select('match', 'light.') | unique | list }}

      color_lights: >
        {% set filtered = namespace(entities=[]) %}
        {% for entity in all_entities %}
          {% set modes = state_attr(entity, 'supported_color_modes') or [] %}
          {% if 'hs' in modes or 'rgb' in modes or 'xy' in modes or 'color_temp' in modes %}
            {% set filtered.entities = filtered.entities + [entity] %}
          {% endif %}
        {% endfor %}
        {{ filtered.entities }}
      strobe_lights: >
        {{ all_entities | reject('in', color_lights) | list }}

  - repeat:
      while:
        - condition: template
          value_template: "{{ true }}"
      sequence:
        - variables:
            # Picks individual bulb IDs from the flattened, recursively expanded list
            bop_targets: >
              {{ color_lights | shuffle | batch(bop_num | int) | first | list }}

        - if:
            - condition: template
              value_template: "{{ bop_targets | count > 0 }}"
          then:
            - service: light.turn_on
              target:
                entity_id: "{{ bop_targets }}"
              data:
                brightness_pct: "{{ brightness }}"
                hs_color:
                  - "{{ range(0, 360) | random }}"
                  - 100
                transition: "{{ transition_secs }}"

        - if:
            - condition: template
              value_template: "{{ strobe_lights | count > 0 }}"
          then:
            - service: light.turn_on
              target:
                entity_id: "{{ strobe_lights | shuffle | batch(bop_num | int) | first | list }}"
              data:
                brightness_pct: "{{ [0, brightness | int] | random }}"
                transition: 0.1
        
        - delay:
            seconds: "{{ delay_secs }}"
mode: restart
